In [19]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler 

In [2]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:,3:13].values
Y = dataset.iloc[:,13].values
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [3]:
labelencoder_X_1 = LabelEncoder()
labelencoder_X_2 = LabelEncoder()

#### Encoding string type data to numeric
X[:,1] = labelencoder_X_1.fit_transform(X[:,1])
X[:,2] = labelencoder_X_2.fit_transform(X[:,2])
####


##columntransformer = ColumnTransformer([('one_hot_encoder',OneHotEncoder(),[1])],remainder = 'passthrough')
##X =np.array(columntransformer.fit_transform(X),dtype = np.float)

##### rEmoving dummy trap
onehotencoder = OneHotEncoder(categorical_features = [1],handle_unknown='ignore')
X =onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]
X
#####

C:\Users\Kakashi\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [4]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size= .2,random_state = 0)


In [5]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test =sc.transform(X_test)

In [6]:
import keras
from keras.models import Sequential ##initiate NN
from keras.layers import Dense ## create layers in NN


Using TensorFlow backend.


In [7]:
classifier = Sequential() ##initialize ann classifier
classifier.add(Dense(units=6,kernel_initializer="uniform",activation="relu",input_dim=11)) ##hidden layer & input layer
classifier.add(Dense(units=6,kernel_initializer="uniform",activation="relu")) ## 2nd hidden layer
classifier.add(Dense(units=1,kernel_initializer="uniform",activation="sigmoid")) ## Final Layer

In [8]:
classifier.compile(optimizer="adam",loss="binary_crossentropy",metrics=['accuracy']) ## compile

In [10]:
classifier.fit(X_train,Y_train,batch_size=10,nb_epoch = 100)

Epoch 1/100
1710/8000 [=====>........................] - ETA: 0s - loss: 0.4032 - accuracy: 0.8251

C:\Users\Kakashi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


8000/8000 [==============================] - 1s 92us/step - loss: 0.3959 - accuracy: 0.8345
Epoch 2/100
8000/8000 [==============================] - 1s 87us/step - loss: 0.3959 - accuracy: 0.8364
Epoch 3/100
8000/8000 [==============================] - 1s 88us/step - loss: 0.3952 - accuracy: 0.8356
Epoch 4/100
8000/8000 [==============================] - 1s 86us/step - loss: 0.3955 - accuracy: 0.8353
Epoch 5/100
8000/8000 [==============================] - 1s 86us/step - loss: 0.3957 - accuracy: 0.8336
Epoch 6/100
8000/8000 [==============================] - 1s 87us/step - loss: 0.3953 - accuracy: 0.8357
Epoch 7/100
8000/8000 [==============================] - 1s 86us/step - loss: 0.3952 - accuracy: 0.8354
Epoch 8/100
8000/8000 [==============================] - 1s 87us/step - loss: 0.3955 - accuracy: 0.8349
Epoch 9/100
8000/8000 [==============================] - 1s 86us/step - loss: 0.3950 - accuracy: 0.8354
Epoch 10/100
8000/8000 [==============================] - 1s 86us/step - los

In [17]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred>0.5) ##return true if y_pred>0
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [18]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, y_pred)
cm

array([[1541,   54],
       [ 255,  150]], dtype=int64)

In [16]:
(1509+211)/2000

0.86

In [1]:
import tensorflow as tf
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 1380858266641182761
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 6657650197
locality {
  bus_id: 1
  links {
  }
}
incarnation: 791679280342538294
physical_device_desc: "device: 0, name: GeForce GTX 1080, pci bus id: 0000:07:00.0, compute capability: 6.1"
]
